version: "3"

volumes:
  traefik-letsencrypt:
  factorio_data:
  vrising_data:
  filebrowser_data:
  blog_data:
  counterstrike_data:
  quake3_data:

services:
  # https://github.com/filebrowser/filebrowser
  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser:v2.23.0
    volumes:
      - /:/data
      - vrising_data:/data/vrising
      - factorio_data:/data/factorio
      - quake3_data:/data/quake3
      - blog_data:/data/blog
      - filebrowser_data:/config
    environment:
      - FB_BASEURL=/
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.rule=Host(`files.${DOMAIN_NAME}`)
      - traefik.http.routers.filebrowser.middlewares=auth
      - traefik.http.routers.filebrowser.tls.certresolver=letsencrypt
      - traefik.http.routers.filebrowser.entrypoints=websecure
      - traefik.http.services.filebrowser.loadbalancer.server.port=8080
      - traefik.http.middlewares.auth.basicauth.usersfile=.htpasswd

  # https://github.com/OpenFactorioServerManager/factorio-server-manager/wiki/Installation-and-Usage
  factorio:
    image: ofsm/ofsm:latest
    container_name: factorio
    environment:
      - FACTORIO_VERSION=stable
    volumes:
      - factorio_data:/opt/fsm-data
    labels:
      - traefik.enable=true
      - traefik.http.routers.fsm.rule=Host(`factorio.${DOMAIN_NAME}`)
      - traefik.http.routers.fsm.tls.certresolver=letsencrypt
      - traefik.http.routers.fsm.entrypoints=websecure
      - traefik.http.services.fsm.loadbalancer.server.port=80
      - traefik.udp.routers.fsm.entrypoints=factorio
      - traefik.udp.services.fsm.loadbalancer.server.port=34197

  # https://github.com/TrueOsiris/docker-vrising
  # server not starting...
  # vrising:
  #   container_name: vrising
  #   image: trueosiris/vrising
  #   network_mode: bridge
  #   environment:
  #     - TZ=Europe/Paris
  #     - SERVERNAME=vrisingDocker
  #   volumes:
  #     - vrising_data:/mnt/vrising/server
  #     - vrising_data:/mnt/vrising/persistentdata
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.vrising.rule=Host(`vrising.${DOMAIN_NAME}`)
  #     - traefik.http.routers.vrising.tls.certresolver=letsencrypt
  #     - traefik.http.routers.vrising.entrypoints=websecure
  #     - traefik.http.services.vrising.loadbalancer.server.port=80
  #     - traefik.udp.routers.vrising.entrypoints=vrising1,vrising2
  #     - traefik.udp.services.vrising.loadbalancer.server.port=9877
  #     - traefik.udp.services.vrising.loadbalancer.server.port=9876

  # https://github.com/traefik/traefik
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    container_name: traefik
    command:
      - --api=true
      - --api.dashboard=true

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.blog-upload.address=:873
      - --entrypoints.factorio.address=:34197/udp
      # - --entrypoints.cs16.address=:27015/udp
      # - --entrypoints.q3.address=:27960/udp
      # - --entrypoints.q3h.address=:27960
      # - --entrypoints.q3js.address=:27960
      # - --entrypoints.vrising1.address=:9877/udp
      # - --entrypoints.vrising2.address=:9876/udp

      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --log.level=DEBUG

      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    restart: unless-stopped
    ports:
      - 80:80 # http
      - 443:443 # https
      - 873:873 # blog-upload rsync port
      # - 27960:27960/udp # quake3 game port
      # - 27960:27960 # quake3 game port
      - 34197:34197/udp # factorio game port
      # - 9877:9877/udp # vrising1 game port
      # - 9876:9876/udp # vrising2 game port
      # - 27015:27015 # cs16 game port
      # - 27015:27015/udp # cs16 game port
    volumes:
      - traefik-letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.middlewares.auth.basicauth.usersfile=.htpasswd

  # https://github.com/amir20/dozzle
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.10.11
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN_NAME}`)
      - traefik.http.routers.dozzle.middlewares=auth
      - traefik.http.routers.dozzle.tls.certresolver=letsencrypt
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.middlewares.auth.basicauth.usersfile=.htpasswd

  # https://hub.docker.com/_/nginx
  blog:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.25.0-alpine3.17
    volumes:
      - blog_data:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.blog.rule=Host(`blog.${DOMAIN_NAME}`)
      - traefik.http.routers.blog.tls.certresolver=letsencrypt
      - traefik.http.routers.blog.entrypoints=websecure

  # https://hub.docker.com/r/axiom/rsync-server
  blog-upload:
    image: axiom/rsync-server
    container_name: blog-upload
    restart: unless-stopped
    volumes:
      - blog_data:/data
    environment:
      - USERNAME=${SSH_USERNAME}
      - PASSWORD=${SSH_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.blog-upload.rule=Host(`blog-upload.${DOMAIN_NAME}`)
      - traefik.http.routers.blog-upload.tls.certresolver=letsencrypt
      - traefik.http.routers.blog-upload.entrypoints=websecure
      - traefik.tcp.routers.blog-upload.entrypoints=blog-upload
      - traefik.tcp.routers.blog-upload.rule=HostSNI(`*`)
      - traefik.tcp.services.blog-upload.loadbalancer.server.port=873

  # https://hub.docker.com/r/febley/counter-strike_server
  # counter-strike_server:
  #   container_name: counter-strike_server
  #   image: febley/counter-strike_server:latest
  #   restart: unless-stopped
  #   environment:
  #     - PORT=27015
  #     - MAP=de_dust2
  #     - MAXPLAYERS=16
  #     - SV_LAN=0
  #   volumes:
  #     - counterstrike_data:/hlds/cstrike
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.cs16.rule=Host(`cs16.${DOMAIN_NAME}`)
  #     - traefik.http.routers.cs16.tls.certresolver=letsencrypt
  #     - traefik.http.routers.cs16.entrypoints=websecure
  #     - traefik.http.services.cs16.loadbalancer.server.port=27015
  #     - traefik.udp.routers.cs16.entrypoints=cs16
  #     - traefik.udp.services.cs16.loadbalancer.server.port=27015

  # https://github.com/fpiesche/docker-ioquake3-server
  # quake3:
  #   image: florianpiesche/ioquake3-server
  #   container_name: quake3_server
  #   restart: unless-stopped
  #   volumes:
  #     - quake3_data:/usr/local/games/quake3/baseq3
  #   environment:
  #     SERVER_MOTD: "UI Foundation Quake 3 Serve"
  #     # ADMIN_PASSWORD: "uifoundation"
  #     # SERVER_ARGS: "+set net_ip 172.18.0.3"
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.quake3.rule=Host(`quake3.${DOMAIN_NAME}`)
  #     - traefik.http.routers.quake3.tls.certresolver=letsencrypt
  #     - traefik.http.routers.quake3.entrypoints=websecure
  #     - traefik.http.services.quake3.loadbalancer.server.port=27960
  #     - traefik.udp.routers.quake3.entrypoints=q3,q3h
  #     - traefik.udp.services.quake3.loadbalancer.server.port=27960

  # https://github.com/treyyoder/quakejs-docker
  # HTTP only, need to disable redirect to HTTPS to make it work
  # quake3js:
  #   image: treyyoder/quakejs:latest
  #   container_name: quake3js
  #   restart: unless-stopped
  #   volumes:
  #     - quake3_data:/usr/local/games/quake3/baseq3
  #   labels:
  #     - traefik.enable=true

  #     - traefik.http.routers.q3js.service=q3js
  #     - traefik.http.routers.q3js.rule=Host(`q3js.${DOMAIN_NAME}`)
  #     - traefik.http.routers.q3js.entrypoints=web
  #     - traefik.http.services.q3js.loadbalancer.server.port=80

  #     - traefik.http.routers.q3js2.service=q3js2
  #     - traefik.http.routers.q3js2.rule=Host(`q3js.${DOMAIN_NAME}`)
  #     - traefik.http.routers.q3js2.entrypoints=q3js
  #     - traefik.http.services.q3js2.loadbalancer.server.port=27960
